main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('add/<int:item_id>/',add_amount, name='add_amount'),
    path('delete/<int:item_id>/',delete_amount, name='delete_amount'),
    path('remove/<int:item_id>/',remove_item, name='remove_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('html/', show_html, name='show_html'), 
    path('json/', show_json, name='show_json'), 
    path('register/', register, name='register'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', create_ajax, name='create_ajax'),
    path('delete-item-ajax/<int:item_id>/', delete_item_ajax, name='delete_item_ajax'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('html/<int:id>/', show_html_by_id, name='show_html_by_id'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
    path('jsonf/',show_json_user, name='show_json_user'),
]

shopeeng/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "amount", "description"]

main/views.py
import datetime
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    total_items = Item.objects.filter(user=request.user).count()
    context = {
        'name': request.user.username,
        'class': 'PBP C',
        'items' : items,
        'total_items' : total_items,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def add_amount(request, item_id):
    item = Item.objects.get(pk=item_id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def create_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, price=price, description=description, amount=amount, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, item_id):
    if request.method == "DELETE":
        item = Item.objects.get(pk=item_id, user=request.user)
        item.delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

def delete_amount(request, item_id):
    item = Item.objects.get(pk=item_id)
    if item.amount > 0 :
        item.amount -= 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def remove_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
     item = form.save(commit=False)
     item.user = request.user
     item.save()
     return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_user(request):
    data = Item.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_html(request):
    data = Item.objects.all()
    return render(request, 'items.html', {'items': data})

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_html_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return render(request, 'items.html', {'items': data})

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user_id = int(data['user']),
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            amount = int(data["amount"])
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
{% include 'navbar.html' %}
<div class="px-4">
    <h1 class="text-5xl font-extrabold my-4">Add New Item</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Item" class="btn btn-primary text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm p-3.5 mr-2 mb-2 focus:outline-none"/>
                    <a href="/">
                        <button type="button" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm p-3.5 mr-2 mb-2">
                            Cancel
                        </button>
                    </a>
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

main/templates/items.html
<!DOCTYPE html>
<html>
<head>
    <title>Items List</title>
</head>
<body>
    <h1>Items List</h1>
    <ul>
        {% for item in items %}
            <li>{{ item.name }} - {{ item.description }}</li>
        {% endfor %}
    </ul>
</body>
</html>

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html'%}

<div class = "login w-full mt-20 max-h-screen flex justify-center content-center">
    <div class="bg-slate-100 py-10 px-20 m-4 w-auto rounded-lg shadow-xl">
        <h1 class="text-5xl font-extrabold mt-4 mb-6">Login</h1>
        <form method="POST" action="" class="my-4">
            {% csrf_token %}
            <div class="mb-6">
              <label for="text" class="block mb-2 text-sm font-medium text-gray-900">Username</label>
              <input  type="text" name="username" class="form-control shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="Username" required>
            </div>
            <div class="mb-6">
              <label for="password" class="block mb-2 text-sm font-medium text-gray-900">Password</label>
              <input type="password" name="password" class="form-control shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="Password" required>
            </div>
            <button type="submit" value="Login" class="btn login_btn text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Login</button>
          </form>   
            Don't have an account yet? <a class="text-blue-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm" href="{% url 'main:register' %}">Register</a>
        {% if messages %}
            {% for message in messages %}
                <p class="text-red-600">{{ message }}</p>
            {% endfor %}
        {% endif %}  
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

{% include 'navbar.html' %}

<div class="px-4 ">
    <h1 class="text-4xl my-7 ml-7 font-bold font-sans">Hello {{ name}} from {{ class}}!</h1>
    <h1 class="font-extrabold text-xl text-black">
        Kamu Menyimpan {{total_items}} item
    </h1>
    <div class="flex justify-between" id="msgcontainer">
        <h1 id="msgtext" class="font-extrabold text-5xl text-black"></h1>
        <div class="flex">
            <a href="{% url 'main:create_item' %}" class="flex w-fit justify-self-end text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm p-4 mr-2 mb-2 focus:outline-none">
                <button>
                  Add New Product
                </button>
            </a>
            <button data-modal-target="modal" data-modal-toggle="modal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center 0" type="button">
                Add New Product Modal
            </button>
        </div>
    </div>
    <div id="item_card" class="flex flex-wrap justify-center"></div>
    <div id="modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
        <div class="relative w-full max-w-md max-h-full">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
                <div class="px-6 py-6 lg:px-8">
                    <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Add Item</h3>
                    <form class="space-y-6" id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div>
                            <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
                            <input type="text" name="name" id="name" class="form-control border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " placeholder="Pensil" required>
                        </div>
                        <div>
                            <label for="price" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Price</label>
                            <input type="number" name="price" id="price" class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " placeholder="2000" required>
                        </div>
                        <div>
                            <label for="amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Amount</label>
                            <input type="number" name="amount" id="amount" class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " placeholder="4" required>
                        </div>
                        <div>
                            <label for="description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
                            <textarea name="description" id="description" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " placeholder="Pensil ini adalah" required></textarea>
                        </div>
                        <button type="button" id="button_add" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" data-modal-hide="modal">Add Item</button>
                        <button type="button" class="w-full text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center " data-modal-hide="modal">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div> 
    <h5 class="mt-4">Sesi terakhir login: {{ last_login }}</h5>
</div>

<script>
    const messageText = document.getElementById("msgtext");
    async function getItems() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
    }
    async function refreshItems() {
        document.getElementById("item_card").innerHTML = ""
        const items = await getItems()
        if(items.length > 0){
            messageText.textContent = "Daftar Barang";
        }else{
            messageText.textContent = "Tambah Barang Dulu Yukk";
        }
        let htmlString = ``
        items.forEach((item, index, array) => {
            const isLastItem = index === array.length - 1;
            htmlString += `\n
            <div id="item_card" class="w-[300px] m-4 h-[350px] p-6 ${isLastItem ? 'bg-transparent' : 'bg-white'} border border-gray-200 rounded-lg shadow-xl">
            <div class="flex justify-between">
                <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 ">${item.fields.name}</h5>
                <button type="submit" onclick="deleteItem(${item.pk}); return false;" name="Remove" class="btn btn-danger focus:outline-none text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-2 py-1.5 mb-2">Delete</button>
            </div>
            <div class="bg-slate-500 h-[150px]"> h </div>
            <p class="my-3 font-normal text-gray-700 ">${item.fields.description}</p>
            <div class="flex justify-between">
                <p class="text-xl font-bold text-gray-900 ">Rp.${item.fields.price}</p>
                <a>${item.fields.amount} items</a>
            </div>
            <div class="flex justify-end">
                <a href="add/${item.pk}">
                    <button type="submit" name="Increment" class="btn btn-primary text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-2 py-1.5 mr-2 mb-2 focus:outline-none">+</button>
                </a>
                <a href="delete/${item.pk}">
                    <button type="submit" name="Decrement" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-2 py-1.5 mr-2 mb-2">-</button>
                </a>
            </div>
        </div>
            ` 
        })
        document.getElementById("item_card").innerHTML = htmlString
    }

    refreshItems()

    function addItem() {
        fetch("{% url 'main:create_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }

    function deleteItem(itemId) {
        fetch(`delete-item-ajax/${itemId}`, {
            method: "DELETE",
            
        }).then(refreshItems)
        return false
    }

  document.getElementById("button_add").onclick = addItem
</script>
    
{% endblock content %}

main/templates/navbar.html
<nav class="bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 focus:ring-4 focus:outline-none focus:ring-red-100">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <div>
            <a href="#" class="block text-xl font-extrabold py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-black md:p-0" aria-current="page">Shopeeng</a>
          </div>
          {% if last_login %}
          <a href="{% url 'main:logout' %}">
            <button type="button" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
                Logout
            </button>
          </a>
          {% endif %}
      </div>
    </div>
  </nav>

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
{% include 'navbar.html' %}

<div class = "login w-full mt-10 max-h-screen flex justify-center content-center">
    <div class="bg-slate-100 py-10 px-20 m-4 w-auto rounded-lg shadow-xl">
        <h1 class="text-5xl font-extrabold mt-4 mb-6">Register</h1>
        <form method="POST" >  
            {% csrf_token %}  
            {% for field in form %}
            <p class="my-2 flex flex-col">
                {% if field.errors %}
                <ul class="errorlist">
                    {% for error in field.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <p class="block mb-2 text-sm font-medium text-gray-900">
                    {{ field.label_tag }}
                </p>
                <p class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    {{ field }}
                </p>
            </p>
            {% endfor %}
            <input type="submit" name="submit" value="Daftar" class="btn login_btn text-white my-3 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"/>
        </form> 
            Have an account? <a class="text-blue-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm" href="{% url 'main:login' %}">Sign In</a>
        {% if messages %}
            {% for message in messages %}
                <p class="text-red-600">{{ message }}</p>
            {% endfor %}
        {% endif %}  
    </div>
</div>

{% endblock content %}